export type FieldDefinition = {
  key: string;
  label: string;
  type:
    | 'text'
    | 'textarea'
    | 'number'
    | 'boolean'
    | 'select'
    | 'multiselect'
    | 'url'
    | 'markdown';
  required: boolean;
  placeholder: string | null;
  options: string[] | null;
  default: unknown;
  sortOrder: number;
};

export type CategoryTemplate = {
  name: string;
  icon: string;
  color: string;
  description: string;
  fieldSchema: FieldDefinition[];
};

export const CATEGORY_TEMPLATES: Record<string, CategoryTemplate> = {
  RACES: {
    name: 'Razas',
    icon: '\u{1F465}',
    color: '#8b5cf6',
    description: 'Razas, especies y pueblos del mundo.',
    fieldSchema: [
      {
        key: 'origin',
        label: 'Origen',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 1,
      },
      {
        key: 'traits',
        label: 'Rasgos',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 2,
      },
      {
        key: 'lifespan',
        label: 'Esperanza de vida',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 3,
      },
      {
        key: 'population',
        label: 'Poblacion',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 4,
      },
      {
        key: 'abilities',
        label: 'Habilidades',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 5,
      },
      {
        key: 'language',
        label: 'Idioma',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 6,
      },
      {
        key: 'notable_members',
        label: 'Miembros notables',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 7,
      },
      {
        key: 'is_extinct',
        label: 'Extinta',
        type: 'boolean',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 8,
      },
    ],
  },
  CITIES: {
    name: 'Ciudades',
    icon: '\u{1F3D9}\uFE0F',
    color: '#3db05a',
    description: 'Ciudades, asentamientos y regiones.',
    fieldSchema: [
      {
        key: 'region',
        label: 'Region',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 1,
      },
      {
        key: 'population',
        label: 'Poblacion',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 2,
      },
      {
        key: 'government',
        label: 'Gobierno',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 3,
      },
      {
        key: 'economy',
        label: 'Economia',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 4,
      },
      {
        key: 'climate',
        label: 'Clima',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 5,
      },
      {
        key: 'notable_locations',
        label: 'Ubicaciones notables',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 6,
      },
      {
        key: 'history',
        label: 'Historia',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 7,
      },
      {
        key: 'current_status',
        label: 'Estado actual',
        type: 'select',
        required: false,
        placeholder: null,
        options: [
          'Floreciente',
          'En decadencia',
          'Destruida',
          'Abandonada',
          'Legendaria',
          'Desconocida',
        ],
        default: null,
        sortOrder: 8,
      },
    ],
  },
  MAGIC: {
    name: 'Magia',
    icon: '\u2728',
    color: '#c9a84c',
    description: 'Sistemas de magia, poderes y habilidades.',
    fieldSchema: [
      {
        key: 'source',
        label: 'Fuente',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 1,
      },
      {
        key: 'limitations',
        label: 'Limitaciones',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 2,
      },
      {
        key: 'power_level',
        label: 'Nivel de poder',
        type: 'select',
        required: false,
        placeholder: null,
        options: ['Menor', 'Moderado', 'Mayor', 'Legendario'],
        default: null,
        sortOrder: 3,
      },
      {
        key: 'users',
        label: 'Usuarios',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 4,
      },
      {
        key: 'cost',
        label: 'Costo',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 5,
      },
      {
        key: 'is_learnable',
        label: 'Se puede aprender',
        type: 'boolean',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 6,
      },
      {
        key: 'is_inherited',
        label: 'Es hereditaria',
        type: 'boolean',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 7,
      },
    ],
  },
  RELIGIONS: {
    name: 'Religiones',
    icon: '\u{1F56F}\uFE0F',
    color: '#e09040',
    description: 'Religiones, cultos y creencias.',
    fieldSchema: [
      {
        key: 'deity',
        label: 'Deidad',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 1,
      },
      {
        key: 'founded',
        label: 'Fundacion',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 2,
      },
      {
        key: 'followers',
        label: 'Seguidores',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 3,
      },
      {
        key: 'practices',
        label: 'Practicas',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 4,
      },
      {
        key: 'beliefs',
        label: 'Creencias',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 5,
      },
      {
        key: 'sacred_texts',
        label: 'Textos sagrados',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 6,
      },
      {
        key: 'is_active',
        label: 'Activa',
        type: 'boolean',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 7,
      },
    ],
  },
  ARTIFACTS: {
    name: 'Artefactos',
    icon: '\u2694\uFE0F',
    color: '#e05555',
    description: 'Artefactos, reliquias y objetos especiales.',
    fieldSchema: [
      {
        key: 'origin',
        label: 'Origen',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 1,
      },
      {
        key: 'material',
        label: 'Material',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 2,
      },
      {
        key: 'power',
        label: 'Poder',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 3,
      },
      {
        key: 'current_owner',
        label: 'Dueno actual',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 4,
      },
      {
        key: 'history',
        label: 'Historia',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 5,
      },
      {
        key: 'is_destroyed',
        label: 'Destruido',
        type: 'boolean',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 6,
      },
      {
        key: 'whereabouts',
        label: 'Paradero',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 7,
      },
    ],
  },
  FACTIONS: {
    name: 'Facciones',
    icon: '\u{1F3DB}\uFE0F',
    color: '#50c87a',
    description: 'Facciones, organizaciones y grupos.',
    fieldSchema: [
      {
        key: 'founded',
        label: 'Fundacion',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 1,
      },
      {
        key: 'leader',
        label: 'Lider',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 2,
      },
      {
        key: 'headquarters',
        label: 'Sede',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 3,
      },
      {
        key: 'goals',
        label: 'Objetivos',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 4,
      },
      {
        key: 'methods',
        label: 'Metodos',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 5,
      },
      {
        key: 'allies',
        label: 'Aliados',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 6,
      },
      {
        key: 'enemies',
        label: 'Enemigos',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 7,
      },
      {
        key: 'is_active',
        label: 'Activa',
        type: 'boolean',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 8,
      },
    ],
  },
  LORE: {
    name: 'Lore',
    icon: '\u{1F4DC}',
    color: '#9088a0',
    description: 'Eventos historicos, leyendas y mitos.',
    fieldSchema: [
      {
        key: 'date_in_world',
        label: 'Fecha en el mundo',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 1,
      },
      {
        key: 'participants',
        label: 'Participantes',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 2,
      },
      {
        key: 'causes',
        label: 'Causas',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 3,
      },
      {
        key: 'consequences',
        label: 'Consecuencias',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 4,
      },
      {
        key: 'is_verified',
        label: 'Verificado',
        type: 'boolean',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 5,
      },
    ],
  },
  CREATURES: {
    name: 'Criaturas',
    icon: '\u{1F409}',
    color: '#604080',
    description: 'Criaturas, bestias y seres fantasticos.',
    fieldSchema: [
      {
        key: 'habitat',
        label: 'Habitat',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 1,
      },
      {
        key: 'size',
        label: 'Tamano',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 2,
      },
      {
        key: 'diet',
        label: 'Dieta',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 3,
      },
      {
        key: 'abilities',
        label: 'Habilidades',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 4,
      },
      {
        key: 'behavior',
        label: 'Comportamiento',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 5,
      },
      {
        key: 'danger_level',
        label: 'Nivel de peligro',
        type: 'select',
        required: false,
        placeholder: null,
        options: ['Inofensiva', 'Baja', 'Media', 'Alta', 'Legendaria'],
        default: null,
        sortOrder: 6,
      },
      {
        key: 'is_sapient',
        label: 'Sapiente',
        type: 'boolean',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 7,
      },
    ],
  },
  TECHNOLOGY: {
    name: 'Tecnologia',
    icon: '\u2699\uFE0F',
    color: '#507090',
    description: 'Tecnologia, inventos y herramientas.',
    fieldSchema: [
      {
        key: 'inventor',
        label: 'Inventor',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 1,
      },
      {
        key: 'era',
        label: 'Era',
        type: 'text',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 2,
      },
      {
        key: 'purpose',
        label: 'Proposito',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 3,
      },
      {
        key: 'materials',
        label: 'Materiales',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 4,
      },
      {
        key: 'limitations',
        label: 'Limitaciones',
        type: 'textarea',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 5,
      },
      {
        key: 'is_widespread',
        label: 'Uso extendido',
        type: 'boolean',
        required: false,
        placeholder: null,
        options: null,
        default: null,
        sortOrder: 6,
      },
    ],
  },
  CUSTOM: {
    name: 'Personalizada',
    icon: '\u{1F4C1}',
    color: '#4e4860',
    description: 'Categoria personalizada sin campos predefinidos.',
    fieldSchema: [],
  },
};

export const TEMPLATE_KEYS = Object.keys(CATEGORY_TEMPLATES);
