export const CANONICAL_GENRES = [
  { slug: 'fantasia', label: 'Fantasía' },
  { slug: 'romance', label: 'Romance' },
  { slug: 'ciencia-ficcion', label: 'Ciencia ficción' },
  { slug: 'misterio', label: 'Misterio' },
  { slug: 'thriller', label: 'Thriller' },
  { slug: 'terror', label: 'Terror' },
  { slug: 'drama', label: 'Drama' },
  { slug: 'aventura', label: 'Aventura' },
  { slug: 'accion', label: 'Acción' },
  { slug: 'distopia', label: 'Distopía' },
  { slug: 'historica', label: 'Histórica' },
  { slug: 'paranormal', label: 'Paranormal' },
  { slug: 'suspenso', label: 'Suspenso' },
  { slug: 'comedia', label: 'Comedia' },
  { slug: 'isekai', label: 'Isekai' },
  { slug: 'fanfiction', label: 'Fanfiction' },
] as const;

export const CANONICAL_GENRE_SLUGS = CANONICAL_GENRES.map(
  (genre) => genre.slug,
);

export const GENRE_SLUG_MAPPINGS: Record<string, string> = {
  fantasia: 'fantasia',
  fantasy: 'fantasia',
  romance: 'romance',
  'ciencia-ficcion': 'ciencia-ficcion',
  'sci-fi': 'ciencia-ficcion',
  misterio: 'misterio',
  mystery: 'misterio',
  thriller: 'thriller',
  terror: 'terror',
  horror: 'terror',
  drama: 'drama',
  aventura: 'aventura',
  adventure: 'aventura',
  accion: 'accion',
  distopia: 'distopia',
  dystopia: 'distopia',
  historica: 'historica',
  historical: 'historica',
  paranormal: 'paranormal',
  suspenso: 'suspenso',
  comedia: 'comedia',
  isekai: 'isekai',
  fanfiction: 'fanfiction',
} as const;
